return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		opts = {
			transparent_background = true,
			background = {
				dark = "mocha",
				light = "latte",
			},
			color_overrides = {
				mocha = {
					rosewater = "#ffb59d",
					-- flamingo = "#ffb59d",
					pink = "#fbb0d8",
					mauve = "#c9bfff",
					red = "#fbb0d8",
					maroon = "#fbb0d8",
					peach = "#ffb59d",
					yellow = "#d5c871",
					green = "#d4bee6",
					teal = "#91d5ad",
					sky = "#9dcbfb",
					sapphire = "#a2c9fe",
					blue = "#9dcbfb",
					lavender = "#9dcbfb",
					text = "#e0e2e8",
					subtext1 = "#cccccc",
					subtext0 = "#bbbbbb",
					overlay2 = "#aaaaaa",
					overlay1 = "#999999",
					overlay0 = "#888888",
					surface2 = "#777777",
					surface1 = "#666666",
					surface0 = "#555555",
					base = "#101418",
					mantle = "#101418",
					crust = "#101418",
				},
			},
		},
	},
}
